# Generated by Django 2.1.3 on 2019-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('reporting', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('auto', models.CharField(default='', max_length=200)),
                ('profi', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default='')),
            ],
        ),
    ]
