# Generated by Django 2.1.3 on 2019-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseregister',
            name='firstname',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Имя'),
        ),
    ]
