# Generated by Django 2.1.3 on 2019-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0002_auto_20190301_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseregister',
            name='auto',
            field=models.CharField(default='', max_length=200, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='baseregister',
            name='date',
            field=models.DateTimeField(default='', verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='baseregister',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='baseregister',
            name='lastname',
            field=models.CharField(default='', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='baseregister',
            name='profi',
            field=models.CharField(default='', max_length=200, verbose_name='Специалист, выполняющий заказ'),
        ),
        migrations.AlterField(
            model_name='baseregister',
            name='reporting',
            field=models.CharField(default='', max_length=200, verbose_name='Отчество'),
        ),
    ]
